elasticsearch:
  cluster-nodes: localhost:9300
  index: hometype_store_products
  type: product
  multi-threaded: true
  default-max-connection: 2
  max-connection: 10
  time-out:
    read: 1000000
    connection: 1200000